### ISSUE TITLE
✏️[기능] 방 입장 시 노티피케이션 브로드캐스트

### ISSUE THREAD

**Issue by peace0096** [Project-Kungeon/GameServer#3]
# 📖 Description
클라이언트가 방에 입장할 때마다, 모든 클라이언트에게 노티를 보냅니다.

# 📅 Todo
- [x] 첫 접속 시, 서버 측에서 Player 패킷 Serialize
- [x] Obejct ~ Player 클래스 기반 생성
- [x] GameSessionManager에서 플레이어 정보 관리(Set<GameSession>을 통해 관리)
- [x] Room 입장 후, Room id를 플레이어에게 전달

# ETC
기타사항
